version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:

  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      # If changing build tools be sure to update GeneratorSetup.md in docs
      - run: gradle :schemas:test :generator:test
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit
      - codecov/upload:
          file: schemas/target/jacoco-reports/jacoco.xml
      - codecov/upload:
          file: generator/target/jacoco-reports/jacoco.xml

  release:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      # If changing build tools be sure to update GeneratorSetup.md in docs
      - run: gradle :schemas:release :generator:release
      - store-artifacts:
          path: schemas/build/libs
      - store-artifacts:
          path: generator/build/libs

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
# TODO: Ensure gradle migration is smooth before introducing release job
#  release:
#    jobs:
#      - release:
#          filters:
#            branches:
#              only: master
