version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - run: mvn clean test
      - store_test_results:
          path: schemas/target/surefire-reports
      - store_test_results:
          path: generator/target/surefire-reports
  deploy:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
      steps:
        - checkout
        - run: ./build.sh
workflows:
  version: 2.1
  build_and_test: 
    jobs:
      - build
  increment_version_and_deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
